default: &default
    class: 'TopicFMv2'
    variant: 'fast' # ['fast', 'plus']
    ckpt: {'fast': 'third_party/topicfmv2/pretrained/topicfm_fast.ckpt', 'plus': 'third_party/topicfmv2/pretrained/topicfm_plus.ckpt'}
    match_threshold: 0.2
    imsize: -1
    dim_resized: "max"
    max_n_matches: -1
    no_match_upscale: False
    match_border_rm: 2
    coarse_model_cfg: {"fast": {"nhead": 2, "attention": "full", "n_samples": 0}, "plus": {"nhead": 8, "attention": "linear", "n_samples": 8, "n_topic_transformers": 2}}
example:
    <<: *default
    match_threshold: 0.5
    imsize: -1
hpatch: # this settings follows LoFTR
   <<: *default
   imsize: 480 
   variant: 'fast'
   match_threshold: 0.1 
   match_border_rm: 0 
   n_sampling_topics: 6
   dim_resized: "min" 
   no_match_upscale: True 
   max_n_matches: 1000
# hpatch: # this settings follows Patch2Pix
#     <<: *default
#     variant: 'fast' # change this to "fast" to evaluate TopicFM-fast
#     imsize: 1024 
#     match_threshold: 0.2 
#     match_border_rm: 0
#     n_sampling_topics: 6 # this parameter is used for TopicFM+ only
#     dim_resized: "max" 
#     no_match_upscale: False 
#     max_n_matches: -1 # 1000
# aachen_v1.1:
#     <<: *default
#     imsize: 1200
#     n_sampling_topics: 0
#     match_threshold: 0.2 # Save all matches#
#     max_n_matches: -1
#     pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
#     qt_dthres: 4
#     qt_psize: 48
#     qt_unique: True
#     ransac_thres: [25]
#     sc_thres: 0.0 # Filtering during quantization
#     covis_cluster: True
aachen_v1.1:
    <<: *default
    variant: "fast"
    imsize: 1200
    match_border_rm: 2
    match_threshold: 0.2 # Save all matches#
    # coarse_model_cfg: {"nhead": 8, "attention": "linear", "n_samples": 8, "n_topic_transformers": 2}
    max_n_matches: -1
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    qt_type: "mean" # set this to "max" for TopicFM+
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [25] 
    # ransac_thres: [22] # use this threshold for TopicFM+
    sc_thres: 0.0 # Filtering during quantization
    covis_cluster: True
aachen:
    <<: *default
    imsize: 1600
    no_match_upscale: False
    n_sampling_topics: 6
    match_threshold: 0.2 # Save all matches
    max_n_matches: 3600
    pairs: ['pairs-db-night_benchmark.txt', 'pairs-query-night_benchmark.txt']
    qt_dthres: 2
    qt_psize: 48
    qt_unique: True
    ransac_thres: [5]
    sc_thres: 0.2 # Filtering during quantization
    covis_cluster: False
inloc:
   <<: *default
   variant: "fast"
   imsize: 1024
   match_threshold: 0.2
   n_sampling_topics: 0
   max_n_matches: 5000
   pairs: 'pairs-query-netvlad40-temporal.txt'
   rthres: 48
   skip_matches: 20
# inloc:
#     <<: *default
#     ckpt: 'third_party/topicfmv2/pretrained/topicfmv4.ckpt'
#     imsize: 1024
#     match_threshold: 0.25
#     match_border_rm: 2
#     coarse_model_cfg: {"nhead": 8, "attention": "linear", "n_samples": 8, "n_topic_transformers": 2}
#     max_n_matches: -1 # 5000
#     pairs: 'pairs-query-netvlad40-temporal.txt'
#     rthres: 40 # 48
#     skip_matches: 20
