default: &default
    class: 'TopicFM'
    ckpt: 'pretrained/topicfm/pretrained_epoch28.ckpt'
    match_threshold: 0.2
    imsize: -1
    no_matches_upscale: False
example:
    <<: *default
    match_threshold: 0.5
    imsize: -1
hpatch:
    <<: *default
    imsize: 1024
    no_match_upscale: False
    n_sampling_topics: 4
